nginx:
  build: ./nginx/
  container_name: magento19_nginx
  ports:
    - 80:80
  links:
    - phpfpm
  volumes:
    # app
    - ../src:/var/www/html
    # nginx configs
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    - ./logs/nginx:/var/log/nginx

phpfpm:
  build: ./php/
  container_name: magento19_php
  ports:
    - 9000:9000
  links:
    - mysql
  volumes:
    # app
    - ../src:/var/www/html
    - ./php/php.ini:/usr/local/etc/php/php.ini:ro
    - ./logs/php:/var/log/php

mysql:
  image: mysql:5.7
  container_name: magento19_mysql
  ports:
    - 3306:3306
  volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/sample-db:/usr/local/src
  environment:
    MYSQL_ROOT_PASSWORD: secret_password
    MYSQL_DATABASE: magento1
    MYSQL_USER: magento1
    MYSQL_PASSWORD: 123456

#phpmyadmin:
#  image: phpmyadmin/phpmyadmin
#  restart: always
#  links:
#  - mysql
#  ports:
#  - 8183:80
#  environment:
#    PMA_USER: root
#    PMA_PASSWORD: secret_password
#    PMA_ARBITRARY: 1
